name: reviewdog
on:
  pull_request:
    branches: [ main ]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          eslint_flags: 'src/**/*.{ts,vue}'
          fail_on_error: true
